//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.26 at 02:05:59 PM BST 
//


package org.deltacloud;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.deltacloud package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Limit_QNAME = new QName("http://www.deltacloud.org/deltacloud.xsd", "limit");
    private final static QName _Name_QNAME = new QName("http://www.deltacloud.org/deltacloud.xsd", "name");
    private final static QName _Description_QNAME = new QName("http://www.deltacloud.org/deltacloud.xsd", "description");
    private final static QName _Address_QNAME = new QName("http://www.deltacloud.org/deltacloud.xsd", "address");
    private final static QName _Architecture_QNAME = new QName("http://www.deltacloud.org/deltacloud.xsd", "architecture");
    private final static QName _OwnerId_QNAME = new QName("http://www.deltacloud.org/deltacloud.xsd", "owner_id");
    private final static QName _State_QNAME = new QName("http://www.deltacloud.org/deltacloud.xsd", "state");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.deltacloud
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Enum }
     * 
     */
    public Enum createEnum() {
        return new Enum();
    }

    /**
     * Create an instance of {@link Instances }
     * 
     */
    public Instances createInstances() {
        return new Instances();
    }

    /**
     * Create an instance of {@link PublicAddresses }
     * 
     */
    public PublicAddresses createPublicAddresses() {
        return new PublicAddresses();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Realm }
     * 
     */
    public Realm createRealm() {
        return new Realm();
    }

    /**
     * Create an instance of {@link PrivateAddresses }
     * 
     */
    public PrivateAddresses createPrivateAddresses() {
        return new PrivateAddresses();
    }

    /**
     * Create an instance of {@link Realms }
     * 
     */
    public Realms createRealms() {
        return new Realms();
    }

    /**
     * Create an instance of {@link HardwareProfile }
     * 
     */
    public HardwareProfile createHardwareProfile() {
        return new HardwareProfile();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link HardwareProfiles }
     * 
     */
    public HardwareProfiles createHardwareProfiles() {
        return new HardwareProfiles();
    }

    /**
     * Create an instance of {@link Images }
     * 
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Instance }
     * 
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deltacloud.org/deltacloud.xsd", name = "limit")
    public JAXBElement<String> createLimit(String value) {
        return new JAXBElement<String>(_Limit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deltacloud.org/deltacloud.xsd", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deltacloud.org/deltacloud.xsd", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deltacloud.org/deltacloud.xsd", name = "address")
    public JAXBElement<String> createAddress(String value) {
        return new JAXBElement<String>(_Address_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deltacloud.org/deltacloud.xsd", name = "architecture")
    public JAXBElement<String> createArchitecture(String value) {
        return new JAXBElement<String>(_Architecture_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deltacloud.org/deltacloud.xsd", name = "owner_id")
    public JAXBElement<String> createOwnerId(String value) {
        return new JAXBElement<String>(_OwnerId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deltacloud.org/deltacloud.xsd", name = "state")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

}
